# Generated by Django 4.2.1 on 2023-06-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.TextField(max_length=100)),
                ('corredor', models.TextField(max_length=100)),
                ('prateleira', models.TextField(max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', to_field='nome')),
            ],
        ),
    ]
