# Generated by Django 4.2.1 on 2023-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
