# Generated by Django 4.2.1 on 2023-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='corredor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='prateleira',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='setor',
            field=models.CharField(max_length=100),
        ),
    ]
