# Generated by Django 4.2.1 on 2023-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('funcionario', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargaHoraria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('folhaPonto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('setor', models.CharField(max_length=80)),
            ],
        ),
    ]
