# Generated by Django 4.2.1 on 2023-06-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosHumanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoshumanos',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recursoshumanos',
            name='funcionario',
            field=models.CharField(max_length=80),
        ),
    ]
