# Generated by Django 4.2.1 on 2023-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vender', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal', models.TextField(max_length=100)),
                ('relatorioCompra', models.TextField(max_length=100)),
                ('relatorioVenda', models.TextField(max_length=100)),
            ],
        ),
    ]
